<a href="https://colab.research.google.com/github/2303A52078/23CSBTB39-40/blob/main/AIML_A1_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[0,5,2,1]
list2=[2,8,9,6]
print(list1)
print(list2)
print(type(list1))
print(type(list2))

[0, 5, 2, 1]
[2, 8, 9, 6]
<class 'list'>
<class 'list'>


In [4]:
# Import necessary libraries
import numpy as np
import pandas as pd

# Create lists
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

# Identify their type
print("Type of list1:", type(list1))
print("Type of list2:", type(list2))

Type of list1: <class 'list'>
Type of list2: <class 'list'>


In [5]:
# Perform operations
multiplication = array1 * array2
division = array1 / array2
poweroff = np.power(array1, 2)  # Square each element of array1

# Print results
print("Multiplication:\n", multiplication)
print("Division:\n", division)
print("Power of 2:\n", poweroff)

Multiplication:
 [ 0 40 18  6]
Division:
 [0.         0.625      0.22222222 0.16666667]
Power of 2:
 [ 0 25  4  1]


In [6]:
# Create a textual output
textual_output = f"Addition of Two:\n{array1} + {array2} = {array1 + array2}"

# Print the textual output
print(textual_output)

Addition of Two:
[0 5 2 1] + [2 8 9 6] = [ 2 13 11  7]


In [7]:
# Apply NumPy mathematical functions
sin_values = np.sin(array1)
log_values = np.log(array1)       # Natural logarithm
log2_values = np.log2(array1)     # Base-2 logarithm
exp_values = np.exp(array1)       # Exponential

# Print results
print("Sin values:\n", sin_values)
print("Log values:\n", log_values)
print("Log2 values:\n", log2_values)
print("Exp values:\n", exp_values)

Sin values:
 [ 0.         -0.95892427  0.90929743  0.84147098]
Log values:
 [      -inf 1.60943791 0.69314718 0.        ]
Log2 values:
 [      -inf 2.32192809 1.         0.        ]
Exp values:
 [  1.         148.4131591    7.3890561    2.71828183]


<ipython-input-7-2d7831bd5d2b>:3: RuntimeWarning: divide by zero encountered in log
  log_values = np.log(array1)       # Natural logarithm
<ipython-input-7-2d7831bd5d2b>:4: RuntimeWarning: divide by zero encountered in log2
  log2_values = np.log2(array1)     # Base-2 logarithm
